# Site
title: Lcl Blog
subtitle: 李成龙的博客 | Lcl Blog
author: LiChengLong
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: "https://lcl-101.github.io"        # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: 李成龙的博客 | Lcl Blog
email: 55475188@qq.com
description: "关于前端与设计 | 这里是 @LCL 李成龙 的个人博客，与你一起发现更大的世界。"
keyword: "LCL Blog, 个人网站, 互联网, 前端, 设计, 产品 ,李成龙 ,博客 ,微博,前端工程师,web,pc,html,css,js"
header-img: img/header_img/home-bg.jpg
signature: false #show signature
signature-img:


# SNS settings
# RSS: false
weibo_username:     3932790473
zhihu_username:     li-cheng-long-3-99
github_username:    lcl-101
facebook_username:  100009375981606

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: your-disqus-ID

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 2f96ace42ba3147a98026afaf0265ac3
# Google Analytics
ga_track_id: 'UA-80711026-1'          # Format: UA-xxxxxx-xx
ga_domain: auto


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，我想去看看。"
sidebar-avatar: img/lcl.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
# - archive
# - category

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [
    {
          title: "X_ray",
          href: "http://chengfangpeng.win/"
    },
    {
          title: "刘邦",
          href: "http://iliubang.github.io/"
    },
    {
          title: "陈辉",
          href: "http://chbless.github.io/blog"
    },
    {
          title: "李成龙",
          href: "https://lcl101.cn/"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: beantech

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
deploy:
  type: git
  repository: https://github.com/lcl-101/lcl-101.github.io.git
  branch: master
